package patty

import (
	"fmt"
	"os"
)

const LoaderPath = "patty_loader.lua"

func writeLoaderFile() error {
	content := `-- Generated by Patty. Safe to commit (small), but typically regenerated.
local v = _VERSION or "Lua 5.1"
local majmin = v:match("(%d+%.%d+)") or "5.1"

local function prepend_path(current, addition)
    if current:find(addition, 1, true) then return current end
    return addition .. ";" .. current
end

local share = "./.patty/share/lua/" .. majmin
local lib = "./.patty/lib/lua/" .. majmin

package.path = prepend_path(package.path, share .. "/?.lua")
package.path = prepend_path(package.path, share .. "/?/init.lua")

package.cpath = prepend_path(package.cpath, lib .. "/?.so")
package.cpath = prepend_path(package.cpath, lib .. "/?.dll")
package.cpath = prepend_path(package.cpath, lib .. "/?.dylib")
`

	file, err := os.Create(LoaderPath)
	if err != nil {
		return fmt.Errorf("cannot create %s: %w\n  Check folder permissions in the current directory", LoaderPath, err)
	}
	defer file.Close()

	_, err = file.WriteString(content)
	if err != nil {
		return fmt.Errorf("failed writing to %s: %w", LoaderPath, err)
	}

	return nil
}

func EnsurePattyDir() error {
	if err := os.MkdirAll(".patty", 0o755); err != nil {
		return fmt.Errorf("cannot create .patty directory: %w\n  This is where patty stores installed packages", err)
	}
	return nil
}

func PrintPostInstallHint() {
	fmt.Println("\n  To use your packages, add this to the top of your Lua entrypoint:")
	fmt.Println(`    require("patty_loader")`)
}
